### ISSUE TITLE
Null pointer exception when using signup email

### ISSUE THREAD

**Issue by zmashiah** [jaliss/securesocial#563] opened 2015-07-02 11:51 UTC
The scenario is easy to reproduce:
1. Signup to a site using mail validation
2. Click to complete the registration (and so far so good)
3. Click AGAIN on the link from the email and you get the exception below

Caused by: java.lang.NullPointerException: null
        at securesocial.core.java.BaseUserService.findToken(BaseUserService.java:149) ~[securesocial_2.11-master-SNAPSHOT.jar:master-SNAPSHOT]
        at securesocial.controllers.MailTokenBasedOperations.executeForToken(MailTokenBasedOperations.scala:78) ~[securesocial_2.11-master-SNAPSHOT.jar:master-SNAPSHOT]
        at securesocial.controllers.BaseRegistration$$anonfun$signUp$1.apply(Registration.scala:138) ~[securesocial_2.11-master-SNAPSHOT.jar:master-SNAPSHOT]
        at securesocial.controllers.BaseRegistration$$anonfun$signUp$1.apply(Registration.scala:136) ~[securesocial_2.11-master-SNAPSHOT.jar:master-SNAPSHOT]

**Comment by EnverOsmanov** [comment] 2015-08-17 12:28
Not reproduced with Scala version.

**Comment by jaliss** [comment] 2015-10-29 13:05
I was unable to reproduce this with any of the sample apps.  I'll close this but please re-open if still facing the issue.

**Closed by jaliss** 2015-10-29 13:05 UTC

**Comment by zmashiah** [comment] 2016-08-25 06:16
Turns out this is happening in our app as well, and the scenario we could reproduce this is:
Sign up, press the complete registration and then pressing the complete registration again.
